dist: trusty
sudo: false
language: node_js

node_js:
  - "6"

os:
  - linux

before_install:
  - npm install -g cypress-cli

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - cypress run --record --key 93b229bc-672c-4d26-b1fd-79928914b828 --env host=https://jgodi.github.io/angular-quickstart-lib

after_script:
  - npm run coveralls

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run nightly-publish
